# Change experiment name
name: 'small_testing_neighr'

seed: 0
train_split: 0.7  # Training data is 70% and test data is 30%
train_on_first: false


base_path: '..'  # base path where model weights , tensorboard will be saved
# base_path: '/Users/jianhansong/my-app'
training_dir: 'trained_models'  # base_path + training_dir
tensorboard_dir: 'runs' # base_path + tensorboard_dir

data:
    # base_path: 'data/model_build_inputs'   # base_path + data.base_path (this path) is where all data is saved
    # base_path + data.base_path + data_type_filename
    base_path: 'data/small_data'
    route_filename: 'route_data.json'
    sequence_filename: 'actual_sequences.json'
    travel_times_filename: 'travel_times.json'
    package_data_filename: 'package_data.json'

    use_cache: false
    slice_begin: 0
    slice_end: 10
    max_route_len: 200
    num_link_features: 2
    num_route_features: 2
    tt_pad_value: 5000.0
    route_score: 'high'
    num_neighbors: 4  # Num of surrounding stops to use for same feature set.

batch_size: 10
num_train_epochs: 400
num_grad_steps: 5
learning_rate: 0.01

# save_path: '/Users/Somi/amazon_challenge/trained_models/nn_irl_10_routes/best_model_nn_irl_10_routes.pt'
